import { User, Post, Notification } from './types';

export const currentUser: User = {
  id: 'user-1',
  username: 'ggm_official',
  displayName: 'GGM Basketball',
  avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=GGM&backgroundColor=d35400',
  bio: 'Official GGM Basketball account. Game time.',
  followers: 12500,
  following: 892,
  isVerified: true,
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: 'user-2',
    username: 'coach_mike',
    displayName: 'Coach Mike',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=CM&backgroundColor=2980b9',
    bio: 'Head Coach | 15 years experience | Building champions',
    followers: 8420,
    following: 456,
    isVerified: true,
  },
  {
    id: 'user-3',
    username: 'slam_master',
    displayName: 'Jordan Williams',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=JW&backgroundColor=8e44ad',
    bio: 'Point Guard #23 | Living the dream',
    followers: 5230,
    following: 312,
    isVerified: false,
  },
  {
    id: 'user-4',
    username: 'hoops_queen',
    displayName: 'Aaliyah Jackson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=AJ&backgroundColor=16a085',
    bio: 'Captain | All-Star 2024 | Never settle',
    followers: 15800,
    following: 678,
    isVerified: true,
  },
  {
    id: 'user-5',
    username: 'three_point_king',
    displayName: 'Marcus Chen',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MC&backgroundColor=c0392b',
    bio: 'Shooter | 45% from downtown | Squad goals',
    followers: 3200,
    following: 290,
    isVerified: false,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    author: mockUsers[1],
    content: 'Practice today was intense! The team is looking sharper than ever. Championship mindset starts now. Ready to dominate this season. #GGMBasketball #Champions',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    likes: 234,
    comments: 42,
    reposts: 18,
    isLiked: false,
    isReposted: false,
    hashtags: ['GGMBasketball', 'Champions'],
  },
  {
    id: 'post-2',
    author: mockUsers[2],
    content: 'That buzzer-beater last night still has me hyped! When the ball left my hands, I just knew it was going in. Trust the process, trust the work. #ClutchTime',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    likes: 892,
    comments: 156,
    reposts: 89,
    isLiked: true,
    isReposted: false,
    hashtags: ['ClutchTime'],
  },
  {
    id: 'post-3',
    author: mockUsers[3],
    content: 'Game day energy is different. The crowd, the lights, the pressure—this is what we live for. See you on the court tonight. #GameDay #GGM',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    likes: 1247,
    comments: 203,
    reposts: 156,
    isLiked: false,
    isReposted: true,
    hashtags: ['GameDay', 'GGM'],
  },
  {
    id: 'post-4',
    author: mockUsers[4],
    content: 'Working on my three-point game all summer. Shot 500 threes today. Consistency is key. When you love what you do, the grind doesn\'t feel like work. #ShootersMentaliry #WorkHard',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    likes: 567,
    comments: 78,
    reposts: 34,
    isLiked: false,
    isReposted: false,
    hashtags: ['ShootersMentality', 'WorkHard'],
  },
  {
    id: 'post-5',
    author: mockUsers[1],
    content: 'Proud of how this team has grown. Started the season with raw talent, now we\'re a well-oiled machine. Special shoutout to @hoops_queen for stepping up as captain. Leadership matters.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    likes: 445,
    comments: 67,
    reposts: 23,
    isLiked: true,
    isReposted: false,
  },
  {
    id: 'post-6',
    author: mockUsers[0],
    content: 'Announcing the GGM Summer Camp 2026! Register now for elite training with our championship coaches. Limited spots available. Link in bio. #GGMCamp #NextGeneration',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    likes: 2340,
    comments: 412,
    reposts: 234,
    isLiked: false,
    isReposted: false,
    hashtags: ['GGMCamp', 'NextGeneration'],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    actor: mockUsers[2],
    postId: 'post-1',
    postContent: 'Practice today was intense...',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'comment',
    actor: mockUsers[3],
    postId: 'post-2',
    postContent: 'That buzzer-beater last night...',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'follow',
    actor: mockUsers[4],
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    isRead: false,
  },
  {
    id: 'notif-4',
    type: 'repost',
    actor: mockUsers[1],
    postId: 'post-3',
    postContent: 'Game day energy is different...',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    isRead: true,
  },
  {
    id: 'notif-5',
    type: 'mention',
    actor: mockUsers[1],
    postId: 'post-5',
    postContent: 'Proud of how this team has grown...',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    isRead: true,
  },
  {
    id: 'notif-6',
    type: 'like',
    actor: mockUsers[2],
    postId: 'post-6',
    postContent: 'Announcing the GGM Summer Camp...',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
    isRead: true,
  },
];

export const trendingTopics = [
  { tag: 'GGMBasketball', posts: '12.5K' },
  { tag: 'GameDay', posts: '8.2K' },
  { tag: 'ClutchTime', posts: '5.4K' },
  { tag: 'PlayoffBound', posts: '4.1K' },
  { tag: 'DunkContest', posts: '3.8K' },
];

export const suggestedUsers = mockUsers.slice(1, 4);
